### PR TITLE
Check attributes types

### LINKED ISSUE #283: `ForceReply#force_reply` type and optionality
https://core.telegram.org/bots/api#forcereply

I see, that `force_reply` is not optional argument for `ForceReply` (I'm kind of mad even for this naming).

But it's type is `True`, so it's not `Boolean`: https://github.com/atipugin/telegram-bot-ruby/blob/02de716/lib/telegram/bot/types/force_reply.rb#L7

The library may not require it, send `true` always, but I see difficulties with `dump_type_attributes` Rake task.

What do you think?

### PR DESCRIPTION
**Pull request by AlexWayfer**
And required values, and there are some fixes…

It resolves #283, which is already "stale", but I have no response from you. So, I've decided to fight this issue globally.

### CODE REVIEW

**Comment by AlexWayfer** [comment]
Please, reopen. :disappointed:

**Comment by AlexWayfer** [comment]
@atipugin there is Bot API v7 update. These changes would help us a lot.

**Comment by atipugin** [comment]
@AlexWayfer sorry for the delay. Could you check why CI fails?

**Comment by AlexWayfer** [comment]
> @AlexWayfer sorry for the delay. Could you check why CI fails?

It wasn't easy, but I've done this shortly. I'm ready to update the whole lib to API v7 after this PR.

**Review by atipugin — APPROVED** [review]

**Comment by atipugin** [comment]
@AlexWayfer Thanks, merged!

**Pull request merged**
