### PR TITLE
Scheduling bot updates with provided scheduler

### PR DESCRIPTION
**Pull request by iarkhanhelsky**
### Scheduling bot updates with provided scheduler
Sometimes you need to do some job in _bot thread_. But infinite loop in
Telegram::Bot::Client.listen doesn’t allow this.

So let’s provide scheduler which can trigger updates when we need this.
It is not prefect solution because we need to wait when timeout ended.

### Check client initialisation arguments

Raise exception if meet unknown key in argument list.

### CODE REVIEW

**Comment by atipugin** [comment]
Scheduler is an interesting idea, but could you give me an example of real world usage of it?

Also, what's a point in raising exception if we pass unknown option key? Anyway we use only keys we expect, others are skipped. There is no need to do additional check.

**Comment by iarkhanhelsky** [comment]
Check arguments is just style pattern. I don't insist :) 

Now about scheduler. I want to use bot client inside `eventmachine`, if it loops infinite other tasks never runs. This short snippet illustrates what happens:

```ruby
require 'eventmachine'
EventMachine.run {
    EventMachine.add_periodic_timer(2) {
        # Here is what bot client does
        loop do
            puts "Bar"
            sleep(2)
        end
    }
    # Never runs because of above
    EventMachine.add_periodic_timer(5) { puts "Foo" }
}

```

**Comment by atipugin** [comment]
Got it. I've just refactored `#listen` method and extracted all the logic to another method called `#fetch_updates`. Please update gem up to 0.3.3. Here is an example of using it w/ eventmachine - https://gist.github.com/atipugin/981502265d595afa4599.

Also, you can avoid waiting for request timeout by passing `timeout` option with `0` value. See example above.

**Comment by iarkhanhelsky** [comment]
I think it's not perfect solution too because now you have two access points for listening events. And if someone talented enough to call `#listen` along with `#fetch_updates` result will be undefined. 

I can work with this anyway :) Thanks.

**Comment by atipugin** [comment]
I think it's ok because now you are able to decide how to get updates - in a loop or once. Just think of `#listen` as a syntax sugar.

**Comment by iarkhanhelsky** [comment]
Suppose I can close it now. Thanks again.

**Pull request closed without merging**
