### PR TITLE
extracted types to telegram-bot-types gem

### PR DESCRIPTION
**Pull request by printercu**
Hi! I've extracted types definitions so they can be used with other API clients: https://github.com/telegram-bot-rb/telegram-bot-types

I'll be glad if you support the idea and become collaborator.

I've already added missing type for UserProfilePhotos and some specs there.

### CODE REVIEW

**Comment by printercu** [comment]
I've already added UserProfilePhotos and some specs.

**Comment by atipugin** [comment]
Hi there! Sorry for a delay and thanks for PR! But what do you mean saying "other API clients"?

**Comment by printercu** [comment]
I've made one, and will introduce it little bit later: https://github.com/telegram-bot-rb/telegram-bot.

There are also a lot of implementations https://github.com/search?utf8=%E2%9C%93&q=telegram+bot+ruby and most of them has same Virtus models. I've found your one the most complete and free of unnecessary features. I hope any of existing or new clients will be able to use this types and extend them if they need to.

**Comment by AbdullahAs** [comment]
@printercu thanks for the PR. However I don't think it's a good idea to go with this approach for couple of reasons: 
1. Having multiple gems to serve the same purpose without any meaningful difference doesn't help anyone, it's better if the community focus in maintaining one gem and this one is the best so far.
2. Introducing an extra dependency for the gem is also considered as a bad practice, it's better if we avoid that.

**Comment by printercu** [comment]
Do you mean api clients in the first reason? My telegram-bot gem focuses on integration with rails apps. I had a client, but its tiny indeed: https://github.com/telegram-bot-rb/telegram-bot/blob/master/lib/telegram/bot/client.rb

In fact telegram-bot-types gem aims your first reason: for now there are a lot of telegram bot clients and most of them have implemented virtus models, mostly in the same way. I just wanted to extract them to single gem, so everybody can get updates when someone made fix or added a new type.

However feel free to close this PR if you don't like the idea.

**Comment by onemanstartup** [comment]
Is it really needs Virtus? Maybe it is better to use Dry-Types?

**Comment by ivanovaleksey** [comment]
@onemanstartup yes, we are thinking about migration to dry-types.

**Comment by onemanstartup** [comment]
@ivanovaleksey here is another possible replacement https://github.com/davydovanton/shallow_attributes it's faster and leaner than virtus, and have almost the same api. Maybe it will be even better as replacement.

**Comment by ivanovaleksey** [comment]
Thanks @onemanstartup, I will definitely take a look. You are welcome to checkout PR once it would be done.

**Pull request closed without merging**
