### PR TITLE
Implement Bot API 2.3 changes

### PR DESCRIPTION
**Pull request by ivanovaleksey**
According to Bot API 2.3 [CHANGELOG](https://core.telegram.org/bots/api-changelog#november-21-2016)

> Added new fields channel_post and edited_channel_post to Update.

> Added the new field forward_from_message_id to Message.

> Renamed hide_keyboard to remove_keyboard in ReplyKeyboardRemove for clarity.

### CODE REVIEW

**Comment by atipugin** [comment]
Hey, thx for the PR. Could you also replace `ReplyKeyboardHide` with `ReplyKeyboardRemove`?

**Comment by ivanovaleksey** [comment]
Yes, I will certainly do it.
But I think it will take some time for me. So I decided to make this PR with small fixes first and then make another one with keyboards.
If the time is not so critical (1-2 days) I would just add commit to this PR.

**Comment by atipugin** [comment]
I think we can wait and release new version with all the changes.

**Comment by ivanovaleksey** [comment]
Alright. Thank you!

**Comment by ivanovaleksey** [comment]
@atipugin changing keyboard types seems to be done. I tested it with example from README.
What about Changelog? Will you update it by yourself since it should contain new gem version?

**Comment by atipugin** [comment]
Looks good, merged!

**Pull request merged**
